from pathlib import Path
from datetime import date
import html, json, hashlib

ROOT = Path(__file__).parent
OUT = ROOT / 'dist'
PROJECTS = json.loads((ROOT / 'projects.json').read_text())
ORIGIN = 'https://plexus-development.criyx-ai.chatgpt.site'
LAUNCH = False
EMAIL = 'info@plexusdevelopmentgroup.ca'

def e(value): return html.escape(str(value), quote=True)
def asset(name): return '/assets/' + name
def picture(name, alt='', cls='', eager=False):
    return f'<img class="{cls}" src="{asset(name)}" alt="{e(alt)}" loading="{'eager' if eager else 'lazy'}" decoding="async">'
def link(text, url, variant='outline'):
    return f'<a class="btn btn-{variant}" href="{url}">{text}<span aria-hidden="true">↗</span></a>'
def eyebrow(text): return f'<span class="eyebrow">{text}</span>'
def section_head(kicker, title, text='', action=''):
    return f'<div class="section-head">{eyebrow(kicker)}<div class="section-head-row"><h2>{title}</h2><div>{f"<p>{text}</p>" if text else ""}{action}</div></div></div>'
def intro(kicker, title, text, image_name='', alt=''):
    media=f'<div class="page-cover">{picture(image_name, alt)}</div>' if image_name else ''
    return f'<section class="page-intro wrap">{eyebrow(kicker)}<h1>{title}</h1><p>{text}</p>{media}</section>'

NAV = [
 ('About', '/about/', [('Our company','/about/'),('Leadership','/about/leadership/'),('Our approach','/about/approach/'),('Careers','/careers/')]),
 ('Portfolio','/portfolio/', [('All projects','/portfolio/'),('Residential','/portfolio/?type=Residential'),('Mixed use & land','/portfolio/?type=Land%20%26%20mixed-use'),('Commercial & industrial','/capabilities/')]),
 ('Capabilities','/capabilities/', [('Development','/capabilities/#development'),('Acquisitions','/acquisitions/'),('Land development','/capabilities/#land'),('Asset strategy','/capabilities/#asset')]),
 ('Partnerships','/partners/', [('Capital partners','/partners/capital/'),('Landowners','/partners/landowners/'),('Brokers','/partners/brokers/'),('Municipalities','/partners/municipalities/'),('Submit an opportunity','/acquisitions/#submission')]),
 ('Impact','/impact/', []),
 ('Insights','/insights/', [('Insights','/insights/'),('News & media','/news/'),('Media centre','/media/'),('Search the site','/search/')]),
 ('Contact','/contact/', [])
]

def header():
    items=''.join(f'<li class="nav-item"><a href="{url}">{title}</a>'+(f'<div class="dropdown">'+''.join(f'<a href="{href}">{label}</a>' for label,href in children)+'</div>' if children else '')+'</li>' for title,url,children in NAV)
    mobile=''.join(f'<details><summary>{title}</summary><a href="{url}">Overview</a>'+''.join(f'<a href="{href}">{label}</a>' for label,href in children)+'</details>' if children else f'<a href="{url}">{title}</a>' for title,url,children in NAV)
    return f'''<a class="skip" href="#main">Skip to content</a><header class="header"><div class="header-inner wrap"><a class="logo" href="/" aria-label="Plexus Development Group home">{picture('logo.png','','logo-mark',True)}<span>PLEXUS<small>DEVELOPMENT GROUP</small></span></a><nav class="desktop-nav" aria-label="Main navigation"><ul>{items}</ul></nav><a class="header-cta" href="/acquisitions/#submission">Submit an opportunity <span aria-hidden="true">↗</span></a><button class="menu-button" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open menu"><span></span><span></span></button></div><nav class="mobile-nav" id="mobile-menu" aria-label="Mobile navigation" hidden>{mobile}<a class="mobile-cta" href="/acquisitions/#submission">Submit an opportunity ↗</a></nav></header>'''

def footer():
    return f'''<footer class="footer"><div class="wrap"><div class="footer-top"><div class="footer-statement">{eyebrow('START A CONVERSATION')}<h2>Where could we<br><em>build value together?</em></h2>{link('Contact Plexus','/contact/','gold')}</div><div class="footer-links"><div><h3>Explore</h3><a href="/portfolio/">Portfolio</a><a href="/capabilities/">Capabilities</a><a href="/acquisitions/">Acquisitions</a><a href="/impact/">Our impact</a><a href="/insights/">Insights</a></div><div><h3>Connect</h3><a href="/partners/capital/">Capital partners</a><a href="/partners/landowners/">Landowners</a><a href="/partners/brokers/">Brokers</a><a href="/partners/municipalities/">Municipalities</a><a href="/careers/">Careers</a><a href="/news/">News & media</a></div><div><h3>Halifax office</h3><a href="mailto:{EMAIL}">{EMAIL}</a><a href="tel:+19028099399">+1 902 809 9399</a><p>3845 Joseph Howe Drive, Suite 100<br>Halifax, Nova Scotia</p></div></div></div><div class="footer-logo">Plexus</div><div class="footer-bottom"><span>© 2026 Plexus Development Group</span><div><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/accessibility/">Accessibility</a><a href="/legal/">Legal</a><a href="/media/">Media</a></div><a href="#top">Back to top ↑</a></div></div></footer>'''

def project_url(p): return '/portfolio/' + p['slug'] + '/'
def project_card(p):
    return f'''<article class="project-card" data-project data-type="{e(p['sector'])}" data-stage="{e(p['status'])}" data-search="{e((p['title']+' '+p['location']+' '+p['sector']).lower())}"><a class="project-image" href="{project_url(p)}">{picture(p['image'],p['imageNote']+' for '+p['title'])}<span class="image-chip">{e(p['imageNote'])}</span></a><div class="project-meta"><span>{e(p['sector'])}</span><span>{e(p['status'])}</span></div><h3><a href="{project_url(p)}">{e(p['title'])}</a></h3><div class="project-bottom"><span>{e(p['location'])}<br><small>{e(p['scale'])}</small></span><a href="{project_url(p)}" aria-label="Explore {e(p['title'])}">↗</a></div></article>'''

def map_section():
    pins=[('Lifestyle Enclave','Upper Hammonds Plains','/portfolio/lifestyle-enclave/','55%','47%'),('Two River','Mineville','/portfolio/two-river-mineville/','53%','46%'),('Cornwallis Park','Annapolis County','/portfolio/cornwallis-park/','17%','46%')]
    buttons=''.join(f'<a class="map-pin" style="--x:{x};--y:{y}" href="{url}" aria-label="{name}, {place}. View project"><span class="pin-dot"></span><span class="pin-card"><strong>{name}</strong><small>{place}</small></span></a>' for name,place,url,x,y in pins)
    return f'''<section class="map-section section-dark" id="map"><div class="wrap">{section_head('OUR FOOTPRINT','Growing across Nova Scotia.','Explore locations represented in the documented portfolio. Pins indicate communities, not parcel boundaries.')}<div class="map-layout"><div class="map-frame">{picture('project-locations.webp','Published Nova Scotia location overview map; map markers are from earlier materials and are not a project legend')}{buttons}</div><div class="map-list"><span class="eyebrow">EXPLORE BY PLACE</span><a href="/portfolio/lifestyle-enclave/"><span>01</span> Upper Hammonds Plains <b>↗</b></a><a href="/portfolio/two-river-mineville/"><span>02</span> Mineville <b>↗</b></a><a href="/portfolio/cornwallis-park/"><span>03</span> Annapolis County <b>↗</b></a><p>Additional names in earlier public materials require confirmation before they can be mapped as current projects.</p></div></div></div></section>'''

def stats():
    values=[('102','residential units at Lifestyle Enclave'),('73','acres in the Mineville concept'),('240','acres illustrated at Cornwallis Park'),('3','documented project profiles')]
    return '<section class="stats" aria-label="Plexus at a glance"><div class="wrap"><span class="eyebrow">PLEXUS AT A GLANCE</span><div class="stats-grid">'+''.join(f'<div><strong data-count="{n}">{n}</strong><span>{label}</span></div>' for n,label in values)+'</div><p>Figures describe specific published project materials. Concept values are illustrative, subject to confirmation and are not totals for land owned or an approved development pipeline.</p></div></section>'

def home():
    video='''<video class="hero-video" muted loop playsinline preload="none" poster="/assets/halifax-hero.webp" aria-hidden="true"><source media="(max-width: 699px)" src="/assets/halifax-hero-mobile.mp4" type="video/mp4"><source src="/assets/halifax-hero.mp4" type="video/mp4"></video>'''
    hero=f'''<section class="hero"><div class="hero-media"><picture><source media="(max-width: 699px)" srcset="/assets/halifax-hero-mobile.webp"><img src="/assets/halifax-hero.webp" alt="" loading="eager" fetchpriority="high" decoding="async"></picture>{video}</div><div class="hero-shade"></div><div class="hero-content wrap">{eyebrow('PLEXUS DEVELOPMENT GROUP · NOVA SCOTIA')}<h1>Building communities.<br><em>Creating value.</em><br>Shaping Atlantic Canada.</h1><p>An integrated real estate development, investment and land platform advancing residential, commercial, industrial and mixed-use opportunities across Nova Scotia and Atlantic Canada.</p><div class="hero-actions">{link('Explore our portfolio','/portfolio/','gold')}{link('Partner with Plexus','/partners/','white')}</div></div><div class="hero-foot wrap"><span>Halifax waterfront · drone aerial</span><a href="#glance">Discover Plexus ↓</a></div></section>'''
    featured=f'''<section class="section wrap" id="featured">{section_head('SELECTED DEVELOPMENTS','Real places. Real opportunities.','A closer look at documented work and clearly labelled concepts.',link('View the portfolio','/portfolio/'))}<div class="project-grid featured-grid">{''.join(project_card(p) for p in PROJECTS[:3])}</div></section>'''
    who=f'''<section class="who section"><div class="wrap who-grid"><div>{eyebrow('WHO WE ARE')}<h2>A Nova Scotia platform built for the <em>long view.</em></h2></div><div><p>Plexus Development Group brings development, land and investment thinking together around places that can serve communities and create durable value. Based in Halifax, the group evaluates opportunities across housing, commercial space and strategic land, working with project teams and partners to move ideas through planning and delivery.</p>{link('Get to know Plexus','/about/')}</div></div></section>'''
    capabilities=[('01','Development','From site potential and planning to construction coordination.','/capabilities/#development'),('02','Acquisitions','Evaluating land, operating assets and development opportunities.','/acquisitions/'),('03','Land strategy','Looking at place, infrastructure and long-term use together.','/capabilities/#land'),('04','Asset strategy','Considering how real estate performs beyond initial delivery.','/capabilities/#asset')]
    caps='<section class="section capabilities-home wrap">'+section_head('CAPABILITIES','An integrated approach to real estate.','A connected perspective across the property lifecycle.',link('Explore capabilities','/capabilities/'))+'<div class="capability-grid">'+''.join(f'<a href="{u}"><span>{n}</span><h3>{t}</h3><p>{d}</p><b>↗</b></a>' for n,t,d,u in capabilities)+'</div></section>'
    why=f'''<section class="why section-dark"><div class="wrap why-grid"><div>{eyebrow('WHY PLEXUS')}<h2>Local intelligence.<br><em>Long-term thinking.</em></h2>{link('Our approach','/about/approach/','light')}</div><div><article><span>01</span><h3>Grounded in place</h3><p>Nova Scotia context informs how opportunities are evaluated.</p></article><article><span>02</span><h3>Connected decisions</h3><p>Land, planning, capital, construction and operations are considered together.</p></article><article><span>03</span><h3>Built through relationships</h3><p>Progress depends on constructive work with communities and project partners.</p></article></div></div></section>'''
    gateway=f'''<section class="gateway section wrap">{section_head('WORK WITH US','The next opportunity starts with a conversation.')}<div class="gateway-grid"><div class="gateway-land">{eyebrow('LAND & ACQUISITIONS')}<h3>Have a property or development opportunity?</h3><p>Share a site, asset or idea for preliminary review.</p>{link('Submit an opportunity','/acquisitions/#submission','light')}</div><div class="gateway-capital">{eyebrow('STRATEGIC PARTNERSHIPS')}<h3>Looking to partner with Plexus?</h3><p>Explore a conversation around development, expertise or capital.</p>{link('Discuss a partnership','/partners/capital/','light')}</div></div></section>'''
    impact=f'''<section class="section impact-home wrap"><div class="impact-photo">{picture('community-moments-meals.webp','Community meal activity shown in earlier Plexus public materials')}</div><div>{eyebrow('COMMUNITY & IMPACT')}<h2>Development is measured in the places it creates.</h2><p>Housing supply, responsible land planning and meaningful local relationships are part of the conversation. Our impact page separates documented activity from ambitions still being measured.</p>{link('Explore our impact','/impact/')}</div></section>'''
    leadership=f'''<section class="section leader-home"><div class="wrap"><div>{eyebrow('LEADERSHIP')}<h2>People behind<br><em>the projects.</em></h2><p>Meet the leadership guiding Plexus’s development approach in Nova Scotia.</p>{link('Meet our leadership','/about/leadership/')}</div>{picture('pavneet-singh.webp','Pavneet Singh, Plexus founder and director')}</div></section>'''
    insight=f'''<section class="section wrap">{section_head('PERSPECTIVES','Ideas from the development process.','Practical perspectives on how land becomes real places.',link('Explore insights','/insights/'))}<div class="editorial-grid"><a href="/insights/from-land-to-community/"><span>INSIGHT · DEVELOPMENT</span><h3>From land to community: how a project takes shape</h3><p>What happens between identifying a site and welcoming its first users.</p><b>Read the perspective ↗</b></a><a href="/news/"><span>NEWS & MEDIA</span><h3>Follow documented project updates</h3><p>See the latest public record and the evidence behind each project profile.</p><b>Visit the newsroom ↗</b></a></div></section>'''
    return hero+'<div id="glance">'+stats()+'</div>'+featured+who+map_section()+caps+why+gateway+impact+leadership+insight

def portfolio():
    filters='''<div class="portfolio-tools"><label>Asset class<select id="type-filter"><option value="all">All asset classes</option><option>Residential</option><option>Land &amp; mixed-use</option></select></label><label>Stage<select id="stage-filter"><option value="all">All stages</option><option>Under construction</option><option>Planned</option><option>Planning review</option><option>Pipeline</option></select></label><label>Search<input type="search" id="project-search" placeholder="Project or place"></label><button id="clear-filters" type="button">Clear filters</button></div>'''
    return intro('PORTFOLIO','Places in progress. <em>Potential in view.</em>','Explore project profiles drawn from the current Plexus site and published project materials. Each page distinguishes active work from concept plans.','lifestyle-front.webp','Architectural rendering of Lifestyle Enclave')+f'<section class="section wrap">{section_head('PROJECT DIRECTORY','Explore the portfolio.')}'+filters+f'<p class="results-count" aria-live="polite"></p><div class="project-grid">{"".join(project_card(p) for p in PROJECTS[:3])}</div><p class="no-results" hidden>No projects match these filters.</p></section>'+map_section()+f'''<section class="section wrap pipeline-note">{eyebrow('EARLIER PUBLIC MATERIALS')}<h2>Additional names in the wider record.</h2><p>The Sables, Greenwood, Wilmot, Lucasville, Atholea and other names appear in earlier materials or the client strategy. Scope, status, location and Plexus’s role require confirmation before they are presented as current project profiles.</p>{link('See earlier residential names','/portfolio/residential-pipeline/')}{link('Discuss a specific opportunity','/contact/')}</section>'''

def project_page(p):
    image_name=p['image']; is_lifestyle=p['slug']=='lifestyle-enclave';
    facts=''.join(f'<div><span>{e(k)}</span><strong>{e(v)}</strong></div>' for k,v in p['facts'][:7])
    gallery=''.join(f'<figure>{picture(name,p['title']+' — '+p['imageNote'])}<figcaption>{e(p['imageNote'])}</figcaption></figure>' for name in p['gallery'])
    note=f'<p class="project-caution">{e(p["note"])}</p>'
    case='''<section class="section case-study wrap" id="case-study"><div>{eyebrow('PROJECT STORY')}<h2>A housing opportunity, translated into a community.</h2></div><div><article><span>01 / THE OPPORTUNITY</span><p>A need for additional multi-residential housing in the Halifax region.</p></article><article><span>02 / THE RESPONSE</span><p>A 102-unit apartment community with one- and two-bedroom plus den layouts and shared resident spaces.</p></article><article><span>03 / ON SITE</span><p>Published construction imagery records the building taking shape. Current completion and leasing milestones should be confirmed with the project team.</p></article></div></section>''' if is_lifestyle else ''
    video=f'<div class="project-video"><video controls preload="none" playsinline poster="/assets/lifestyle-drone.webp"><source src="/assets/plexus-overview.mp4" type="video/mp4"></video><p>Lifestyle Enclave construction footage · silent</p></div>' if is_lifestyle else ''
    return f'''<section class="project-hero"><div class="project-hero-image">{picture(image_name,p['imageNote']+' for '+p['title'],eager=True)}</div><div class="project-hero-shade"></div><div class="wrap project-hero-copy"><a class="back-link" href="/portfolio/">← Portfolio</a>{eyebrow(e(p['sector'])+' · '+e(p['status']))}<h1>{e(p['title'])}</h1><p>{e(p['location'])}</p></div><span class="project-hero-caption">{e(p['imageNote'])}</span></section><section class="section wrap project-summary"><div><span class="eyebrow">PROJECT OVERVIEW</span><h2>{e(p['detailHeading'])}</h2><p>{e(p['description'])}</p>{note}</div><div class="fact-grid">{facts}</div></section>{case}<section class="section project-gallery-section"><div class="wrap">{section_head('VISUAL RECORD','See the project.','Images are identified as construction photography or concept/rendering material.')}{video}<div class="project-gallery">{gallery}</div></div></section><section class="section wrap detail-story"><div>{eyebrow('THE DEVELOPMENT VISION')}<h2>Looking beyond the site.</h2></div><div><p>{e(p['detail'])}</p><h3>What the published material shows</h3><ul>{''.join('<li>'+e(item)+'</li>' for item in p['features'][:6])}</ul></div></section><section class="section-dark project-contact"><div class="wrap"><div>{eyebrow('PROJECT ENQUIRIES')}<h2>Talk with Plexus about {e(p['title'])}.</h2></div>{link('Start a conversation','/contact/?topic='+p['slug'],'gold')}</div></section>'''

def about():
    return intro('ABOUT PLEXUS','A local perspective.<br><em>A wider horizon.</em>','Plexus Development Group works from Halifax across development, land and real estate opportunities with a long-term view of value.','lifestyle-arrival.webp','Lifestyle Enclave architectural rendering')+f'''<section class="section wrap split-copy"><div>{eyebrow('OUR STORY')}<h2>Built around opportunity and execution.</h2></div><div><p>Plexus brings together projects and relationships across multi-residential, commercial, industrial and strategic land interests. The company’s public record includes a 102-unit residential development at Lifestyle Enclave and concept-stage communities elsewhere in Nova Scotia.</p><p>Its approach starts with the specific place: the land, the local need, the planning context and the people required to deliver a viable project.</p>{link('Meet the leadership','/about/leadership/')}</div></section><section class="section-dark section"><div class="wrap">{section_head('OUR APPROACH','A practical path from possibility to place.')}<div class="three-columns"><article><span>01</span><h3>Understand</h3><p>Study the site, market, policy and community context.</p></article><article><span>02</span><h3>Align</h3><p>Connect plans, partners, capital and delivery requirements.</p></article><article><span>03</span><h3>Deliver</h3><p>Move deliberately through approvals, construction and operation as applicable.</p></article></div></div></section>'''

def leadership():
    return intro('LEADERSHIP','The people behind <em>the decisions.</em>','Visible leadership and clear responsibility matter in real estate.')+f'''<section class="section wrap leader-profile"><div>{picture('pavneet-singh.webp','Pavneet Singh, founder and director of Plexus')}</div><div>{eyebrow('FOUNDER & DIRECTOR')}<h2>Pavneet Singh</h2><p>Pavneet Singh is presented in Plexus’s public materials as a Halifax-based real estate developer. His work with the group focuses on identifying opportunities, building relationships and coordinating a practical path from land and planning to development.</p><p>Plexus’s published materials connect his perspective to real estate advisory, investment opportunities and community-minded project growth. A fuller transaction history and professional credentials should be added only after verification.</p>{link('Discuss a partnership','/partners/')}</div></section>'''

def approach():
    parts=[('Local intelligence','Understand Nova Scotia’s development context and the needs of each community.'),('Integrated thinking','Consider land, planning, financing, construction and operations together.'),('Partnership mindset','Work constructively with landowners, brokers, specialists, capital sources and public stakeholders.'),('Long-term perspective','Assess how an asset or place functions beyond its first transaction.')]
    return intro('OUR APPROACH','Clear thinking for <em>complex places.</em>','Every opportunity has a different path. Plexus begins with the site and builds the team and strategy around it.')+f'<section class="section wrap">{section_head("WHY PLEXUS","A connected view of development.")}<div class="value-grid">'+''.join(f'<article><h3>{a}</h3><p>{b}</p></article>' for a,b in parts)+'</div></section>'

def capabilities():
    blocks=[('development','Development','Plexus approaches projects from initial site evaluation through concept, planning and construction coordination. The right program follows the site and its market.'),('land','Land development','Land value depends on access, infrastructure, policy, environmental conditions and timing. These factors are assessed before a concept is treated as a commitment.'),('asset','Asset strategy','A development’s operating life matters. Plexus considers use, stewardship and potential long-term ownership as part of the larger real estate decision.'),('partnerships','Development partnerships','Project delivery may involve landowners, specialists, lenders, municipalities and operators. Roles are shaped by the specific opportunity and documented agreement.')]
    sectors=f'''<section class="section sector-focus wrap">{section_head('ASSET FOCUS','Across more than one kind of place.','These are areas Plexus evaluates; inclusion does not imply a current owned or approved project.')}<div class="pill-grid">{''.join('<span>'+x+'</span>' for x in ['Multi-residential','Mixed-use','Commercial','Industrial & logistics','Self-storage','Strategic land','Hospitality'])}</div></section>'''
    return intro('CAPABILITIES','From land and ideas to <em>lasting places.</em>','Development, acquisitions, land strategy and partnerships sit within one connected platform.','lucasville-concept.webp','Illustrative Lucasville commercial concept rendering')+'<section class="section wrap capability-list">'+''.join(f'<article id="{slug}"><span>0{i}</span><div><h2>{title}</h2><p>{desc}</p></div></article>' for i,(slug,title,desc) in enumerate(blocks,1))+'</section>'+sectors+f'<section class="section-dark section"><div class="wrap centered">{eyebrow("HAVE AN OPPORTUNITY?")}<h2>Bring us a site, asset or development idea.</h2>{link("Explore acquisitions","/acquisitions/","gold")}</div></section>'

def partners():
    items=[('Capital partners','Long-term alignment around real assets, clear strategy and disciplined execution.','/partners/capital/'),('Landowners','Explore a direct sale or development conversation around your property.','/partners/landowners/'),('Brokers','Bring forward an on-market or off-market opportunity for preliminary review.','/partners/brokers/'),('Municipalities & communities','Discuss housing, employment lands, local services and thoughtful growth.','/partners/municipalities/')]
    return intro('PARTNERSHIPS','Good projects take <em>good partners.</em>','Plexus works through relationships with people who know the land, the market, the community and the capital needs.')+'<section class="section wrap partner-grid">'+''.join(f'<a href="{url}"><h2>{title}</h2><p>{desc}</p><span>Explore ↗</span></a>' for title,desc,url in items)+'</section>'

def capital():
    return intro('CAPITAL & STRATEGIC PARTNERS','Partnership built around <em>real assets.</em>','Plexus welcomes conversations with organizations seeking a disciplined, project-specific approach to development and real estate.')+f'''<section class="section wrap split-copy"><div>{eyebrow('INVESTMENT APPROACH')}<h2>Alignment begins with a clear project thesis.</h2></div><div><p>Each potential partnership starts with the asset, the development path and the risks that need to be understood. Plexus’s focus spans housing, commercial and strategic land opportunities in Nova Scotia, with Atlantic Canada as a wider area of interest.</p><p>Scope, role, governance, reporting and capital terms belong in private, project-specific discussions supported by diligence.</p>{link('Explore selected projects','/portfolio/')}</div></section><section class="section-dark section"><div class="wrap">{section_head('HOW WE THINK','Disciplined by design.')}<div class="three-columns"><article><span>01</span><h3>Development logic</h3><p>Connect site potential to an achievable program and delivery path.</p></article><article><span>02</span><h3>Risk awareness</h3><p>Assess planning, costs, timing, counterparties and operational needs.</p></article><article><span>03</span><h3>Partner alignment</h3><p>Define responsibilities, information flow and decision points for each relationship.</p></article></div><p class="legal-inline">This page is general company information. It is not an offer to sell securities or a promise of investment returns.</p></div></section><section class="section wrap centered">{eyebrow('DISCUSS A PARTNERSHIP')}<h2>Start a private conversation.</h2>{link('Contact Plexus','/contact/?topic=capital','gold')}</section>'''

def landowners():
    return intro('FOR LANDOWNERS','Your land may be the beginning of <em>something bigger.</em>','Plexus evaluates sites for their location, planning context and potential long-term use.')+f'''<section class="section wrap split-copy"><div><h2>A conversation shaped around your property.</h2></div><div><p>A direct acquisition, conditional purchase or development partnership may be considered where the site and the parties align. Any structure depends on due diligence and agreement.</p><p>Share the address, parcel information, site size and what you hope to achieve. The more context you provide, the better the preliminary review.</p>{link('Discuss your property','/acquisitions/#submission','gold')}</div></section>'''

def brokers():
    return intro('FOR BROKERS','Great opportunities begin with <em>great relationships.</em>','Plexus welcomes relevant on-market and off-market opportunities across Nova Scotia and Atlantic Canada.')+f'''<section class="section wrap split-copy"><div><h2>Bring the details. We’ll review the fit.</h2></div><div><p>Property type, location, size, zoning, income and approvals help determine the right next conversation. Plexus values professional communication, confidentiality where agreed and recognition of the people who introduce an opportunity.</p><p>Broker arrangements and information-sharing terms should be confirmed directly with the acquisition team.</p>{link('Submit a deal','/acquisitions/#submission','gold')}</div></section>'''

def municipalities():
    return intro('MUNICIPALITIES & COMMUNITIES','Working together on <em>places that last.</em>','Housing, employment space, infrastructure and local services work best when plans respond to community context.')+f'''<section class="section wrap split-copy"><div><h2>Development is a shared process.</h2></div><div><p>Plexus aims to engage the planning, policy and infrastructure questions that shape each site. Conversations with municipalities and communities can clarify housing needs, transportation, servicing, environmental considerations and the right scale of development.</p><p>Specific project commitments and impact measures are published only when verified.</p>{link('Start a conversation','/contact/?topic=municipality','gold')}</div></section>'''

def impact():
    return intro('OUR IMPACT','Places matter beyond <em>the property line.</em>','Plexus’s community and environmental ambitions are grounded in project-specific decisions and evidence.','community-moments-bags.webp','Community activity shown in earlier Plexus public materials')+f'''<section class="section wrap impact-areas">{section_head('FOCUS AREAS','What we can measure, and what we are building toward.')}<div class="value-grid"><article><h3>Housing</h3><p>Lifestyle Enclave is documented as a 102-unit residential community under construction in Upper Hammonds Plains.</p></article><article><h3>Community</h3><p>Earlier Plexus material shows community activity. Programme names, dates and contribution amounts need confirmation before they become impact claims.</p></article><article><h3>Environment</h3><p>Project materials mention EV charging options and green space. Performance data such as energy, water and emissions is not yet published.</p></article><article><h3>Partnerships</h3><p>Local work depends on contractors, consultants and public stakeholders. Named organizational logos are reserved for approved use.</p></article></div></section>'''

def insights():
    return intro('INSIGHTS','Perspectives on <em>real estate and place.</em>','Practical writing from the development process. Market statistics will be published here when a sourced research programme is in place.')+f'''<section class="section wrap"><div class="editorial-grid"><a href="/insights/from-land-to-community/"><span>DEVELOPMENT PROCESS</span><h2>From land to community: how a project takes shape</h2><p>A plain-language guide to site evaluation, planning, delivery and operation.</p><b>Read article ↗</b></a><a href="/portfolio/"><span>PROJECT RECORD</span><h2>Explore the documented Plexus portfolio</h2><p>Project pages separate construction evidence from proposed concepts.</p><b>Explore projects ↗</b></a></div></section>'''

def article():
    return intro('INSIGHT · DEVELOPMENT PROCESS','From land to community: <em>how a project takes shape.</em>','A useful project starts with the right questions, not a rendering.')+'''<article class="article-body wrap"><p class="article-lead">Development is a sequence of decisions. Each stage tests whether an opportunity can become a place that works for its residents, neighbours, partners and operators.</p><h2>1. Understand the site</h2><p>Location, access, services, planning policy, environmental conditions and market demand shape what a property can realistically support. An early concept is a hypothesis to test, not an approval.</p><h2>2. Build the development case</h2><p>A project team studies design, cost, schedule, financing, risk and the people who will use the place. The most useful plans connect those elements rather than treating architecture as a standalone exercise.</p><h2>3. Work through approvals and delivery</h2><p>Planning, consultation, design development, procurement and construction all create new information. Scope and timing can change as that information becomes clearer.</p><h2>4. Think past opening day</h2><p>Operations, maintenance, accessibility and energy use influence long-term value. A development succeeds when it remains useful after the first transaction or lease.</p><div class="article-cta"><h3>See how these ideas appear in the portfolio.</h3><a href="/portfolio/">Explore projects ↗</a></div></article>'''

def news():
    return intro('NEWS & MEDIA','The public record, <em>in context.</em>','Project updates and company announcements will appear here when milestones and publication rights are confirmed.')+f'''<section class="section wrap news-feature"><div>{eyebrow('CURRENT PROJECT RECORD')}<h2>Lifestyle Enclave construction imagery</h2><p>The project profile includes a construction aerial and architectural renderings published through Plexus and the Lifestyle Enclave project site. Current occupancy and leasing details should be confirmed directly with the project team.</p>{link('Explore project record','/portfolio/lifestyle-enclave/')}</div>{picture('lifestyle-drone.webp','Lifestyle Enclave construction aerial')}</section>'''

def media():
    return intro('MEDIA CENTRE','A clear source for <em>Plexus information.</em>','For media enquiries, approved imagery and company information, contact the Plexus team.')+f'''<section class="section wrap media-grid"><article>{eyebrow('COMPANY PROFILE')}<h2>About Plexus</h2><p>Plexus Development Group is a Halifax-based real estate development, investment and land platform focused on opportunities across Nova Scotia and Atlantic Canada.</p>{link('Read our story','/about/')}</article><article>{eyebrow('PROJECT IMAGES')}<h2>Project photography</h2><p>Project pages identify construction imagery and illustrative material. Publication or reuse rights should be arranged with Plexus.</p>{link('Request media assets','/contact/?topic=media')}</article><article>{eyebrow('PRESS CONTACT')}<h2>Get in touch</h2><p>Send your outlet, deadline and the project or subject you are covering.</p><a href="mailto:{EMAIL}?subject=Media%20enquiry">{EMAIL} ↗</a></article></section>'''

def careers():
    return intro('CAREERS','Build what’s next <em>with Plexus.</em>','Plexus’s work touches development, project delivery, operations and relationships across Nova Scotia.')+f'''<section class="section wrap split-copy"><div><h2>Join a team working across real estate and place.</h2></div><div><p>There are no verified open positions listed at this time. If your experience is relevant to development, project management, property operations, finance or administration, you can introduce yourself to the team.</p><p>Students, consultants and vendors can use the same contact route and identify their area of interest.</p><a href="mailto:{EMAIL}?subject=Careers%20at%20Plexus" class="btn btn-gold">Introduce yourself <span aria-hidden="true">↗</span></a></div></section>'''

def field(label, name, type='text', required=False, placeholder=''):
    req=' required' if required else ''
    return f'<label>{label}{" <span>*</span>" if required else ""}<input name="{name}" type="{type}"{req} placeholder="{e(placeholder)}"></label>'
def select(label,name,options,required=False):
    return f'<label>{label}{" <span>*</span>" if required else ""}<select name="{name}"{" required" if required else ""}><option value="">Select one</option>'+''.join(f'<option>{e(o)}</option>' for o in options)+'</select></label>'
def form_note(): return '<p class="form-disclosure">This static preview prepares an email draft in your email app. Your message is sent only when you review and send that email. Files cannot be uploaded through this preview; attach documents to the email draft. See our <a href="/privacy/">privacy policy</a>.</p>'
def acquisitions():
    fields=field('Contact name','name',required=True)+field('Company','company')+field('Email','email','email',True)+field('Telephone','phone','tel')+select('Relationship to property','relationship',['Owner','Broker','Advisor','Other'],True)+field('Property address','address',required=True)+field('PID','pid')+field('Municipality','municipality')+select('Asset type','asset_type',['Multi-residential','Development land','Commercial','Industrial','Mixed-use','Self-storage','Hospitality','Strategic land','Other'],True)+field('Site area','site_area')+field('Existing building area','building_area')+field('Current zoning','zoning')+field('Asking price','asking_price')+field('Existing income','income')+select('Approval status','approvals',['Unknown','No approvals','In process','Approved','Other'])+select('Environmental studies available?','environmental',['Yes','No','Unknown'])+select('Survey available?','survey',['Yes','No','Unknown'])+select('Development plans available?','plans',['Yes','No','Unknown'])
    form=f'''<form class="lead-form" data-mail-form data-subject="Property opportunity"><div class="form-grid">{fields}</div><label>Tell us about the opportunity <span>*</span><textarea name="description" rows="5" required></textarea></label><label class="check"><input type="checkbox" name="consent" required><span>I consent to Plexus Development Group contacting me about this opportunity.</span></label><div class="form-honey" aria-hidden="true"><label>Leave blank<input name="website" tabindex="-1" autocomplete="off"></label></div><button class="btn btn-gold" type="submit">Prepare opportunity email <span aria-hidden="true">↗</span></button>{form_note()}<p class="form-status" role="status"></p></form>'''
    return intro('ACQUISITIONS','Bring us your <em>next opportunity.</em>','Plexus evaluates development land, operating assets and strategic real estate opportunities throughout Nova Scotia and Atlantic Canada.','lifestyle-drone.webp','Lifestyle Enclave construction aerial')+f'''<section class="section wrap">{section_head('WHAT WE CONSIDER','A broad view of real estate potential.')}<div class="pill-grid">{''.join('<span>'+x+'</span>' for x in ['Multi-residential','Development land','Commercial','Industrial','Mixed-use','Self-storage','Hospitality','Strategic land assemblies'])}</div></section><section class="section-dark section" id="submission"><div class="wrap acquisition-layout"><div>{eyebrow('SUBMIT AN OPPORTUNITY')}<h2>Share the property story.</h2><p>Start with the basics. An address, asset type, zoning and available studies help the team understand the site. Supporting material can be attached when you send the prepared email.</p></div>{form}</div></section>'''

def search_page():
    return intro('SITE SEARCH','Find the right <em>conversation.</em>','Search projects, places, capabilities and company information.')+'''<section class="section wrap site-search"><label for="site-query">Search Plexus</label><input id="site-query" type="search" placeholder="Try Mineville, land or capital"><p class="search-count" aria-live="polite"></p><div class="search-results" aria-live="polite"></div></section>'''

def contact():
    fields=field('Full name','name',required=True)+field('Company','company')+field('Email address','email','email',True)+field('Telephone','phone','tel')+select('I am a','audience',['Capital partner','Landowner','Broker','Tenant','Municipality','Consultant','Contractor','Media','Job applicant','Other'],True)
    form=f'''<form class="lead-form" data-mail-form data-subject="Plexus website enquiry"><div class="form-grid">{fields}</div><label>How can we help? <span>*</span><textarea name="message" rows="6" required></textarea></label><label class="check"><input type="checkbox" name="consent" required><span>I consent to Plexus Development Group contacting me about this enquiry.</span></label><div class="form-honey" aria-hidden="true"><label>Leave blank<input name="website" tabindex="-1" autocomplete="off"></label></div><button class="btn btn-gold" type="submit">Prepare enquiry email <span aria-hidden="true">↗</span></button>{form_note()}<p class="form-status" role="status"></p></form>'''
    return intro('CONTACT','Start a <em>conversation.</em>','Tell us what brings you here and we will connect you with the right next discussion.')+f'''<section class="section wrap contact-layout"><div><h2>Let’s talk about what comes next.</h2><p>Head office</p><address>3845 Joseph Howe Drive, Suite 100<br>Halifax, Nova Scotia</address><a href="tel:+19028099399">+1 902 809 9399</a><a href="mailto:{EMAIL}">{EMAIL}</a><div class="contact-visual">{picture('halifax-hero.webp','Aerial view of the Halifax waterfront in Nova Scotia')}</div></div>{form}</section>'''

def policy(title, intro_text, sections):
    return intro('SITE INFORMATION',title,intro_text)+'<section class="article-body wrap">'+''.join(f'<h2>{h}</h2><p>{p}</p>' for h,p in sections)+'</section>'

PAGES = {
 '':('Real Estate Development in Nova Scotia',home,'An integrated real estate development, investment and land platform advancing opportunities across Nova Scotia and Atlantic Canada.'),
 'portfolio':('Real Estate Development Portfolio',portfolio,'Explore documented Plexus residential, land and mixed-use project profiles in Nova Scotia.'),
 'about':('About Plexus Development Group',about,'Learn about the Halifax-based development, investment and land platform.'),
 'about/leadership':('Plexus Leadership',leadership,'Meet the leadership of Plexus Development Group in Halifax, Nova Scotia.'),
 'about/approach':('Our Development Approach',approach,'How Plexus evaluates land, partnerships and real estate development opportunities.'),
 'capabilities':('Real Estate Development Capabilities',capabilities,'Development, land, acquisitions, asset strategy and partnerships in Nova Scotia.'),
 'partners':('Development and Real Estate Partnerships',partners,'Explore opportunities to work with Plexus as a landowner, broker, capital partner or municipality.'),
 'partners/capital':('Capital and Strategic Partners',capital,'Discuss project-specific real estate development partnerships with Plexus.'),
 'partners/landowners':('For Landowners',landowners,'Discuss a property or development land opportunity with Plexus.'),
 'partners/brokers':('For Real Estate Brokers',brokers,'Submit relevant development, commercial or land opportunities to Plexus.'),
 'partners/municipalities':('Municipalities and Communities',municipalities,'Work with Plexus on context-aware housing and real estate development.'),
 'acquisitions':('Real Estate Acquisitions',acquisitions,'Submit development land, operating assets and strategic properties for preliminary Plexus review.'),
 'impact':('Community and Environmental Impact',impact,'Explore documented community, housing and environmental information from Plexus projects.'),
 'insights':('Real Estate Development Insights',insights,'Practical perspectives on land, development and real estate in Nova Scotia.'),
 'insights/from-land-to-community':('From Land to Community',article,'A guide to the stages that take a site from evaluation to operation.'),
 'news':('News and Media',news,'Project updates and verified announcements from Plexus Development Group.'),
 'media':('Plexus Media Centre',media,'Company profile, project images and press contact for Plexus Development Group.'),
 'careers':('Careers at Plexus',careers,'Explore future work and introduce yourself to Plexus Development Group.'),
 'contact':('Contact Plexus Development Group',contact,'Contact the Halifax Plexus team about real estate projects, land and partnerships.'),
 'search':('Search Plexus Development Group',search_page,'Search Plexus projects, locations, development capabilities and partnership information.'),
 'privacy':('Privacy Policy',lambda:policy('Your information, <em>your choice.</em>','How this website handles information you choose to share.', [('Email enquiries','Forms on this static preview prepare a draft in your email application. No information is submitted to the website by completing a form. Your email provider and Plexus’s receiving system process the message after you send it.'),('Website functions','The website uses locally hosted fonts, images and video. It has no authored advertising trackers. Hosting providers may process technical access logs needed to serve and secure the site.'),('Contact',f'Questions about information sent to Plexus can be directed to {EMAIL}.')]),'How Plexus website enquiry drafts and basic website functions handle information.'),
 'terms':('Terms of Use',lambda:policy('Website terms <em>of use.</em>','Please use project information as a starting point for a direct conversation.', [('Project information','Illustrations, concepts, dimensions, uses and timing may change. Confirm current details with Plexus before relying on a project description.'),('Images and content','Images and written content are for viewing this website. Please request permission before reusing them.'),('External sites','Links to third-party websites are provided for convenience and may have separate terms.')]),'Terms governing use of Plexus website and project content.'),
 'accessibility':('Accessibility',lambda:policy('Access for <em>everyone.</em>','Plexus aims to make its website usable across devices and assistive technologies.', [('Using this site','The site provides keyboard navigation, visible focus, text alternatives and reduced-motion support. Please contact us if a page or document is difficult to use.'),('Feedback',f'To request information in a different format or report an access barrier, email {EMAIL}.')]),'Accessibility information and feedback contact for Plexus Development Group.'),
 'legal':('Legal Disclaimer',lambda:policy('Important <em>information.</em>','How to interpret the development and partnership information on this website.', [('Development concepts','Concept plans, areas, unit counts and amenity ideas are illustrative unless expressly stated otherwise. They do not establish ownership, approvals, availability or delivery dates.'),('Capital partnerships','This website provides general company information. It is not an offer to sell securities, a solicitation to invest or a promise of returns. Any prospective transaction requires separate documentation and professional review.'),('Accuracy','Plexus aims to keep information current, but project status and terms can change. Confirm material facts directly with the company.')]),'Important disclaimers for Plexus project concepts and capital partnership information.')
}

for p in PROJECTS:
    page_title = 'Residential Development Pipeline' if p['slug']=='residential-pipeline' else p['title']+' Real Estate Project'
    PAGES['portfolio/'+p['slug']] = (page_title,lambda p=p:project_page(p),p['description'][:155])

search_index=[{'title':title,'url':'/'+(route+'/' if route else ''),'description':description} for route,(title,_,description) in PAGES.items() if route not in ('search','privacy','terms','legal','accessibility')]
(OUT/'search-index.json').write_text(json.dumps(search_index,ensure_ascii=False))

def ld_json(route,title):
    org={'@context':'https://schema.org','@type':'Organization','name':'Plexus Development Group','url':ORIGIN+'/','email':EMAIL,'telephone':'+1-902-809-9399','address':{'@type':'PostalAddress','streetAddress':'3845 Joseph Howe Drive, Suite 100','addressLocality':'Halifax','addressRegion':'NS','addressCountry':'CA'}}
    crumbs=route.split('/') if route else []
    items=[{'@type':'ListItem','position':1,'name':'Home','item':ORIGIN+'/'}]
    for i in range(len(crumbs)):
        path='/'.join(crumbs[:i+1]);items.append({'@type':'ListItem','position':i+2,'name':crumbs[i].replace('-',' ').title(),'item':ORIGIN+'/'+path+'/'})
    return '<script type="application/ld+json">'+json.dumps(org,ensure_ascii=False).replace('<','\\u003c')+'</script>'+('<script type="application/ld+json">'+json.dumps({'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':items},ensure_ascii=False)+'</script>' if route else '')

def write(route,title,body,description):
    path=OUT/route/'index.html';path.parent.mkdir(parents=True,exist_ok=True)
    url=ORIGIN+'/'+(route+'/' if route else '')
    robots='index,follow,max-image-preview:large' if LAUNCH else 'noindex,nofollow'
    markup=f'''<!doctype html><html lang="en-CA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} | Plexus Development Group</title><meta name="description" content="{e(description)}"><meta name="robots" content="{robots}"><meta name="theme-color" content="#101d2b"><link rel="canonical" href="{url}"><meta property="og:type" content="website"><meta property="og:site_name" content="Plexus Development Group"><meta property="og:title" content="{e(title)} | Plexus Development Group"><meta property="og:description" content="{e(description)}"><meta property="og:url" content="{url}"><meta property="og:image" content="{ORIGIN}/assets/og-image.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/logo.png"><link rel="stylesheet" href="/revamp.css"><script src="/revamp.js" defer></script>{ld_json(route,title)}</head><body id="top">{header()}<main id="main">{body}</main>{footer()}</body></html>'''
    path.write_text(markup)

for route,(title,fn,description) in PAGES.items(): write(route,title,fn(),description)

# Keep earlier public URLs working while the information architecture changes.
redirects={'projects':'portfolio','projects/lifestyle-enclave':'portfolio/lifestyle-enclave','projects/two-river-mineville':'portfolio/two-river-mineville','projects/cornwallis-park':'portfolio/cornwallis-park','projects/residential-pipeline':'portfolio','residential':'portfolio','commercial':'capabilities','industrial':'capabilities','community':'impact'}
for old,new in redirects.items():
    path=OUT/old/'index.html';path.parent.mkdir(parents=True,exist_ok=True)
    dest='/'+new+'/'
    path.write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex"><meta http-equiv="refresh" content="0;url={dest}"><link rel="canonical" href="{ORIGIN}{dest}"><title>Page moved | Plexus Development Group</title></head><body><p>This page has moved to <a href="{dest}">{dest}</a>.</p></body></html>')

routes=list(PAGES)
urls='\n'.join(f'<url><loc>{ORIGIN}/{r+"/" if r else ""}</loc><lastmod>{date.today().isoformat()}</lastmod></url>' for r in routes)
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="utf-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls+'</urlset>')
(OUT/'robots.txt').write_text(f'User-agent: *\n{"Allow: /" if LAUNCH else "Disallow: /"}\n'+(f'Sitemap: {ORIGIN}/sitemap.xml\n' if LAUNCH else ''))
(OUT/'404.html').write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found | Plexus Development Group</title><link rel="stylesheet" href="/revamp.css"></head><body>{header()}<main class="not-found wrap"><span class="eyebrow">404 · PAGE NOT FOUND</span><h1>Let’s find the right place.</h1><p>The page you requested may have moved.</p>{link("Explore the portfolio","/portfolio/","gold")}</main>{footer()}</body></html>')
print(f'Generated {len(routes)} pages and {len(redirects)} legacy redirects.')
